services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: app_golang
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure

volumes:
  postgres_data:

networks:
  merch-network:
    driver: bridge